spring:
  application:
    name: demo-config
  jmx:
    enabled: false
  cloud:
    config:
      server:
        git:
          uri: file://D:/Temp/14/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8081