spring:
  application:
    name: demo-config
  jmx:
    enabled: false
  cloud:
    config:
      server:
        git:
          uri: file://D:/Temp/1017spring-config-repo
  mvc:
    log-request-details: on
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8081
logging:
  level:
    org.springframework: debug
