spring:
  application:
    name: demo-eureka-server
  jmx:
    enabled: false
  mvc:
    log-request-details: on
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1000
    hostname: localhost
logging:
  level:
    org.springframework: debug
