spring:
  application:
    name: demo-app
  jmx:
    enabled: false
  cloud:
    config:
      discovery:
        enabled: true
        service-id: demo-config
  config:
    import: "configserver:"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8082
logging:
  level:
    org.springframework: debug
